version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Radeonares
      MONGO_INITDB_ROOT_PASSWORD: KirilmaNoktasi42
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Radeonares
      ME_CONFIG_MONGODB_ADMINPASSWORD: KirilmaNoktasi42
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
